github:
  description: "Apache XML Graphics Commons"
  homepage: https://xmlgraphics.apache.org/commons/
  labels:
    - xgc
    - apache
  enabled_merge_buttons:
    merge:   false      # disable non-squashing merge
    squash:  true
    rebase:  true
  protected_branches:
    main:
      strict: true
      required_linear_history: true
      required_signatures: true
  dependabot_alerts:  true
  dependabot_updates: false

notifications:
  commits: commits@xmlgraphics.apache.org
  # issues: general@xmlgraphics.apache.org
  # pullrequests: general@xmlgraphics.apache.org
  # jobs: general@xmlgraphics.apache.org
  jira_options: link label
